// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//
// Created by vogje01 on 9/7/26.
//

// Euclid includes
#include <ListenerCertificate.h>
#include <euclid/core/CertificateUtils.h>
#include <euclid/core/Configuration.h>
#include <euclid/core/DateTimeUtils.h>
#include <euclid/core/ErnUtils.h>
#include <euclid/core/LogStream.h>
#include <euclid/core/SystemUtils.h>
#include <euclid/database/RepositoryFactory.h>

namespace Euclid::EAG {

    namespace asio = boost::asio;

    namespace {

        // The name a listener's certificate has when its configuration does not name one. Per
        // namespace, because that is what a listener is: two ports serving different namespaces
        // are different front doors and should not be made to share a certificate by accident.
        std::string defaultCertificateName(const std::string &nameSpace) {
            return nameSpace.empty() ? "eag" : "eag-" + nameSpace;
        }

        Database::Entity::EKM::Certificate generate(const std::string &accountId, const std::string &nameSpace, const std::string &name) {

            const auto &configuration = Core::Configuration::instance();

            // The name callers will use in a URL, which is what their client checks the
            // certificate against. Configurable because this process cannot know it: it sees a
            // port, not the name somebody typed.
            const auto hostName = Core::SystemUtils::GetHostName();
            const auto commonName = configuration.getOr<std::string>("euclid.modules.eag.certificate-common-name",
                                                                     hostName.empty() ? std::string("localhost") : hostName);

            // localhost and the loopback address alongside it, so that a certificate generated on
            // a developer's machine also works for the way they will actually reach it.
            std::vector<std::string> altNames{"localhost", "127.0.0.1", "::1"};
            if (!hostName.empty()) altNames.push_back(hostName);

            const auto generated = Core::CertificateUtils::GenerateSelfSigned(commonName, altNames);

            Database::Entity::EKM::Certificate certificate;
            certificate.accountId = accountId;
            certificate.region = configuration.getOr<std::string>("euclid.region", "");
            certificate.nameSpace = nameSpace;
            certificate.name = name;
            certificate.description = "Generated by the API gateway because listener '" + (nameSpace.empty() ? std::string("default") : nameSpace) + "' had no certificate";
            certificate.certificatePem = generated.certificate;
            certificate.privateKeyPem = generated.privateKey;
            certificate.generated = true;

            if (const auto info = Core::CertificateUtils::Inspect(certificate.certificatePem)) {
                certificate.subject = info->subject;
                certificate.issuer = info->issuer;
                certificate.serialNumber = info->serialNumber;
                certificate.fingerprint = info->fingerprint;
                certificate.subjectAltNames = info->subjectAltNames;
                certificate.notBefore = info->notBefore;
                certificate.notAfter = info->notAfter;
            }
            certificate.ern = Core::createEkmCertificateErn(accountId, nameSpace, name);

            auto stored = Database::RepositoryFactory::instance().ekmRepository()->upsertCertificate(certificate);

            // Said as a warning rather than logged quietly: every caller of this port will be
            // shown a certificate nobody has vouched for, and whoever runs the installation should
            // find out from the log rather than from a browser.
            log_warning << "No certificate '" << name << "' for the API gateway, generated a self-signed one, subject: "
                        << stored.subject << ", fingerprint: " << stored.fingerprint
                        << ", expires: " << Core::DateTimeUtils::ToISO8601(stored.notAfter);
            return stored;
        }

    }// namespace

    // Which account the listener's certificate belongs to. There is no caller to ask - this runs
    // while the module is starting - so it comes from the installation's own account list. With
    // several configured the first is taken and said so, because a certificate stored under an
    // account nobody looks in is worse than one stored under the wrong one.
    std::string ListenerAccountId() {

        const auto &configuration = Core::Configuration::instance();
        if (const auto configured = configuration.getOr<std::string>("euclid.modules.eag.account-id", ""); !configured.empty()) {
            return configured;
        }
        if (configuration.has("euclid.account-ids")) {
            if (const auto accounts = configuration.getArray<std::string>("euclid.account-ids"); !accounts.empty()) {
                if (accounts.size() > 1) {
                    log_info << "Several accounts are configured; API gateway certificates belong to " << accounts.front()
                             << ". Set euclid.modules.eag.account-id to choose another.";
                }
                return accounts.front();
            }
        }
        return {};
    }

    std::string ListenerCertificateName(const std::string &certificateName, const std::string &nameSpace) {
        return certificateName.empty() ? defaultCertificateName(nameSpace) : certificateName;
    }

    std::shared_ptr<asio::ssl::context> LoadListenerCertificate(const std::string &certificateName, const std::string &nameSpace) {

        const auto accountId = ListenerAccountId();
        if (accountId.empty()) {
            throw std::runtime_error("No account is configured (euclid.account-ids), so a listener certificate has nowhere to belong");
        }
        const auto name = ListenerCertificateName(certificateName, nameSpace);

        auto certificate = Database::RepositoryFactory::instance().ekmRepository()->findCertificateByName(accountId, nameSpace, name);
        if (!certificate.has_value()) {
            certificate = generate(accountId, nameSpace, name);
        } else {
            log_info << "API gateway listener certificate, name: " << name << ", subject: " << certificate->subject
                     << ", expires: " << Core::DateTimeUtils::ToISO8601(certificate->notAfter);

            // Only reported, never refused: a certificate that expired an hour ago still serves
            // the callers whose clients do not check, and taking the port down would take away
            // the one thing left that works while a replacement is fetched.
            if (certificate->notAfter != std::chrono::system_clock::time_point{} && certificate->notAfter < std::chrono::system_clock::now()) {
                log_error << "The API gateway listener certificate '" << name << "' expired on "
                          << Core::DateTimeUtils::ToISO8601(certificate->notAfter) << " and callers will refuse it";
            }
        }

        if (certificate->certificatePem.empty() || certificate->privateKeyPem.empty()) {
            throw std::runtime_error("Certificate '" + name + "' has no certificate or no private key");
        }

        auto context = std::make_shared<asio::ssl::context>(asio::ssl::context::tlsv12_server);
        context->set_options(asio::ssl::context::default_workarounds | asio::ssl::context::no_sslv2
                             | asio::ssl::context::no_sslv3 | asio::ssl::context::single_dh_use);

        // The chain rather than the single certificate: whatever intermediates were imported with
        // it are what a client needs to build a path to a trust anchor it already has.
        context->use_certificate_chain(asio::buffer(certificate->certificatePem));
        context->use_private_key(asio::buffer(certificate->privateKeyPem), asio::ssl::context::pem);
        return context;
    }

}// namespace Euclid::EAG
