.TH EUCLID-CLI-EKM-CREATE-KEY 1 "August 2026" "euclid-cli 1.0.33" "Euclid CLI Manual"
.SH NAME
euclid-cli-ekm-create-key \- create a new encryption key
.SH SYNOPSIS
.B euclid-cli ekm create-key
.BR \-\-algorithm | \-a
.I ALGORITHM
[\fB\-\-length\fR|\fB\-l\fR \fIBITS\fR]
.SH DESCRIPTION
Creates a new key with the given algorithm and key length. Default
length is 128 bit.
.SH OPTIONS
.TP
.BR \-a ", " \-\-algorithm " " \fIALGORITHM\fR
Key type, possible values are \fIaes\fR, \fIaes-gcm\fR. Required.
.TP
.BR \-l ", " \-\-length " " \fIBITS\fR
Key length, \fI128\fR or \fI256\fR. Defaults to \fI128\fR.
.SH EXIT STATUS
.TP
.B 0
The key was created; its ERN, name, algorithm and length are printed as
JSON.
.TP
.B 1
Missing/invalid arguments, the server could not be reached, or the
server rejected the request (e.g. an unsupported algorithm or length).
.SH EXAMPLES
.RS
.nf
euclid-cli --endpoint http://localhost:5566 ekm create-key \e
    --algorithm aes --length 128

euclid-cli --endpoint http://localhost:5566 ekm create-key \e
    --algorithm aes-gcm --length 256
.fi
.RE
.SH SEE ALSO
.BR euclid-cli-ekm (1),
.BR euclid-cli-ekm-list-keys (1),
.BR euclid-cli-ekm-revoke-key (1),
.BR euclid-cli-ekm-delete-key (1),
.BR euclid-cli-ekm-encrypt (1),
.BR euclid-cli-ekm-decrypt (1)
.SH AUTHOR
Jens Vogt <jens.vogt@opitz-consulting.com>
