.TH EUCLID-CLI-EAM-USER-GROUP-REMOVE-USER 1 "August 2026" "euclid-cli 1.0.53" "Euclid CLI Manual"
.SH NAME
euclid-cli-eam-user-group-remove-user \- remove a user from a Euclid user group
.SH SYNOPSIS
.B euclid-cli
[\fB\-\-endpoint\fR \fIURL\fR]
.B eam user-group-remove-user
.BR \-\-user\-group | \-g
.I ERN
.BR \-\-user | \-u
.I ERN
.SH DESCRIPTION
Removes a user from a user group via the eam service's
.I user-group-remove-user
action. The caller must be authenticated as an administrator (see
.BR euclid-cli-eam-login (1)).
.PP
Both the group and the user are identified by their Euclid resource name
(ERN), not by their bare name/user ID - see
.BR euclid-cli-eam-list-user-groups (1)
and
.BR euclid-cli-eam-list-users (1)
to look them up.
.PP
If the group is named
.IR administrator ,
removing a user from it revokes that user's administrator privileges -
take care not to remove the last administrator, since there is no other
way to regain administrator access short of the register bootstrap
exception on a completely empty user store.
.SH OPTIONS
.TP
.BR \-g ", " \-\-user\-group " " \fIERN\fR
ERN of the user group to remove the user from. Required.
.TP
.BR \-u ", " \-\-user " " \fIERN\fR
ERN of the user to remove. Required.
.SH EXIT STATUS
.TP
.B 0
The user was removed from the group.
.TP
.B 1
Missing/invalid arguments, the request could not be sent, the caller is
not an authenticated administrator, or the group or user ERN does not
exist. If the failure was an expired or invalid session (\fIHTTP 401\fR),
the stored credentials file is removed; run
.B euclid-cli eam login
again before retrying.
.SH EXAMPLES
Revoke jdoe's administrator privileges:
.RS
.nf
euclid-cli --endpoint http://localhost:5566 eam user-group-remove-user \e
    --user-group ern:eam:eu-central-1:000000000000:userGroup:administrator \e
    --user ern:eam:eu-central-1:000000000000:user:jdoe
.fi
.RE
.SH SEE ALSO
.BR euclid-cli-eam (1),
.BR euclid-cli-eam-login (1),
.BR euclid-cli-eam-user-group-add-user (1),
.BR euclid-cli-eam-list-user-groups (1)
.SH AUTHOR
Jens Vogt <jens.vogt@opitz-consulting.com>
