.TH EUCLID-CLI-ESM-SET-OBJECT-ATTRIBUTE 1 "August 2026" "euclid-cli 1.0.53" "Euclid CLI Manual"
.SH NAME
euclid-cli-esm-set-object-attribute \- change the value of an existing object attribute
.SH SYNOPSIS
.B euclid-cli esm set-object-attribute
.BR \-\-ern | \-e
.I ERN
.BR \-\-name | \-n
.I NAME
.BR \-\-value | \-v
.I VALUE
[\fB\-\-type\fR|\fB\-t\fR \fITYPE\fR]
.SH DESCRIPTION
Sets the value of an attribute the object already carries. The
attribute must exist - this action does not create one, so a mistyped
name is reported instead of quietly adding an attribute nobody meant
to store. Use
.BR euclid-cli-esm-add-object-attribute (1)
to add a new one.
.PP
The type may differ from the value's previous type: an attribute
stored as a string can be replaced by a number. Prints the stored
attribute as JSON on success.
.SH OPTIONS
.TP
.BR \-e ", " \-\-ern " " \fIERN\fR
Euclid resource name of the object. Required.
.TP
.BR \-n ", " \-\-name " " \fINAME\fR
Name of the attribute to change. Required.
.TP
.BR \-v ", " \-\-value " " \fIVALUE\fR
New value, as text; interpreted according to
.BR \-\-type .
Required.
.TP
.BR \-t ", " \-\-type " " \fITYPE\fR
Type of the value: one of \fIint\fR, \fIlong\fR, \fIdouble\fR,
\fIfloat\fR, \fIbool\fR, \fIstring\fR or \fIbinary\fR. Defaults to
\fIstring\fR.
.SH EXIT STATUS
.TP
.B 0
The attribute was updated. The stored attribute is printed as JSON.
.TP
.B 1
Missing/invalid arguments, the server could not be reached, no object
with that ERN exists, the object belongs to another account, or the
object has no attribute of that name.
.SH EXAMPLES
.RS
.nf
euclid-cli --endpoint http://localhost:5566 esm set-object-attribute \e
    --ern ern:esm:eu-central-1:000000000000:development:object:mix/PIM-4269.xml \e
    --name revision --value 8 --type long
.fi
.RE
.SH SEE ALSO
.BR euclid-cli-esm (1),
.BR euclid-cli-esm-add-object-attribute (1),
.BR euclid-cli-esm-list-object-attributes (1),
.BR euclid-cli-esm-delete-object-attribute (1)
.SH AUTHOR
Jens Vogt <jens.vogt@opitz-consulting.com>
