.TH EUCLID-CLI-EQS-GET-MESSAGE-METADATA 1 "August 2026" "euclid-cli 1.0.53" "Euclid CLI Manual"
.SH NAME
euclid-cli-eqs-get-message-metadata \- show a message's metadata
.SH SYNOPSIS
.B euclid-cli eqs get-message-metadata
.BR \-\-message\-id | \-m
.I MESSAGE-ID
.SH DESCRIPTION
Shows a message's metadata: messageId, queueErn, receiptHandle, status,
priority, size (bytes), receivedCount, visibilityTimeout, contentType,
md5Body, md5Attributes, created, modified.
.SH OPTIONS
.TP
.BR \-m ", " \-\-message\-id " " \fIMESSAGE-ID\fR
ID of the message to query. Required.
.SH EXIT STATUS
.TP
.B 0
The message's metadata is printed as JSON.
.TP
.B 1
Missing/invalid arguments, the server could not be reached, or no
message with that ID exists.
.SH EXAMPLES
.RS
.nf
euclid-cli --endpoint http://localhost:5566 eqs get-message-metadata \e
    --message-id 6f1b1e2e-...
.fi
.RE
.SH SEE ALSO
.BR euclid-cli-eqs (1),
.BR euclid-cli-eqs-list-messages (1),
.BR euclid-cli-eqs-get-message-attribute (1),
.BR euclid-cli-eqs-set-visibility (1)
.SH AUTHOR
Jens Vogt <jens.vogt@opitz-consulting.com>
