.TH EUCLID-CLI-ESM-DELETE-OBJECT 1 "August 2026" "euclid-cli 1.0.53" "Euclid CLI Manual"
.SH NAME
euclid-cli-esm-delete-object \- delete a storage object
.SH SYNOPSIS
.B euclid-cli esm delete-object
.BR \-\-ern | \-e
.I ERN
.SH DESCRIPTION
Deletes a storage object identified by its Euclid resource name (ERN).
This cannot be undone.
.SH OPTIONS
.TP
.BR \-e ", " \-\-ern " " \fIERN\fR
Euclid resource name of the object to delete. Required.
.SH EXIT STATUS
.TP
.B 0
The object was deleted. No output is printed.
.TP
.B 1
Missing/invalid arguments, the server could not be reached, or no
object with that ERN exists.
.SH EXAMPLES
.RS
.nf
euclid-cli --endpoint http://localhost:5566 esm delete-object \e
    --ern ern:euclid:storage:eu-central-1:000000000000:object:2026-08.csv
.fi
.RE
.SH SEE ALSO
.BR euclid-cli-esm (1),
.BR euclid-cli-esm-upload-file (1),
.BR euclid-cli-esm-list-objects (1)
.SH AUTHOR
Jens Vogt <jens.vogt@opitz-consulting.com>
